### ISSUE TITLE
Runs are not visible

### ISSUE THREAD

**Issue by jennifer12121** [aimhubio/aimos#7]
## ❓Question

Hello, I ran [this base example](https://github.com/aimhubio/aimos/blob/09d3add83aab22071c1fcd3731c94f7aa2af9bb4/examples/base.py) and attempted to track to a remote server. No errors were thrown, but the runs never made it to the dashboard. I then logged directly into the server and ran the same example to try tracking an experiment locally and no errors were thrown, but nothing appears in the dashboard. With the new cli options (aimos vs aim) would you be able to provide information on how to list all the runs to see if they are getting stored in the database, but maybe just not displaying in the ui?

**Comment by jennifer12121** [comment]
I was able to see a single run that was created locally by running `aimos containers --repo /aim ls`. I tried to track a second run and received this error: 

`repo = Repo(path='/aim', read_only=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/aimos/_sdk/repo.py", line 193, in __init__
    self._storage_engine = LocalStorage(self.path, read_only=read_only)
  File "/usr/local/lib/python3.8/site-packages/aimos/_sdk/local_storage.py", line 26, in __init__
    self.container: StorageContainer = RocksContainer(self.path, read_only=read_only)
  File "src/python/aimos/_core/storage/rockscontainer.pyx", line 109, in aimos._core.storage.rockscontainer.RocksContainer.__init__
  File "src/python/aimos/_core/storage/rockscontainer.pyx", line 160, in aimos._core.storage.rockscontainer.RocksContainer.db
  File "src/aimrocks/lib_rocksdb.pyx", line 1706, in aimrocks.lib_rocksdb.DB.__cinit__
  File "src/aimrocks/lib_rocksdb.pyx", line 89, in aimrocks.lib_rocksdb.check_status
aimrocks.errors.RocksIOError: b'IO error: While lock file: /aim/.aim/data/LOCK: Resource temporarily unavailable'`.

Would you be able to provide a workaround for this?
